baseURL: "https://isiko.github.io/"
languageCode: en
title: isiko404
theme: "PaperMod"
publishdir: docs
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: isi_ko404's Site
  description: "I'm isi_ko404, a student from NRW Germany, having Fun with Programming. I'll post about my projects around here, and maby a bit about what I do offline. Also, I'm not that good at writing, so bear with me."
  keywords: [Blog, Portfolio, PaperMod, Coding]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["profile.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"

  label:
    text: "isi_ko404"
    icon: /profile.png
    iconHeight: 32

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: isi_ko404
    subtitle: "Self taught Programmer in Java (Kotlin) and NodeJS. Did Stuff with HTML, CSS, and Python. Also exploring the possibilities of ROS."
    imageUrl: "profile.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Projects
        url: projects
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/isi_ko404"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/12111269"
    - name: github
      url: "https://github.com/isiko"
    - name: e-mail
      url: "mailto:koerner@informatik-ag.net"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
  #   URL: "https://github.com/isiko/isiko.github.io/tree/main/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 10
    - identifier: contact
      name: contact
      url: /contact
      weight: 10
    # - identifier: blog
    #   name: blog
    #   url: /projects/
    #   weight: 20
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai